# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - id: setupJava8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - id: setupJava11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - id: setupJava17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: cactuslab/maven-toolchains-xml-action@v1
        with:
          outputFile: toolchains.xml
          toolchains: |
            [
              {"jdkVersion": "8", "jdkHome": "${{steps.setupJava8.outputs.path}}"},
              {"jdkVersion": "11", "jdkHome": "${{steps.setupJava11.outputs.path}}"},
              {"jdkVersion": "17", "jdkHome": "${{steps.setupJava17.outputs.path}}"}
            ]

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: settings.xml
          servers: '[{ "id": "some-server", "username": "some.user", "password": "some.password" }]'
      - id: show
        run: |
          cat toolchains.xml
          cat settings.xml
